[cassandra]
# ACTUALIZADO: Debe coincidir con el nuevo container_name del nodo semilla
hostname = mathews-cassandra-seed
jmx_port = 7199

[storage]
storage_provider = google_storage
# ACTUALIZADO: El nombre del bucket que definiste en tu componente de mongo_backup
bucket_name = mathews-coffee-bucket
key_file = /credentials/gcp_key.json
prefix = mathews-cluster-backups
concurrent_transfers = 4

[grpc]
enabled = false